services:

  backend:
    image: "${REGISTRY:-ghcr.io/henrymanke}/${IMAGE_NAME:-conduit}/backend:${IMAGE_TAG:-latest}"
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - backend-data:/usr/src/app/
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys, urllib.request; sys.exit(urllib.request.urlopen('http://localhost:8000/admin/login/').getcode() != 200)"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: "${REGISTRY:-ghcr.io/henrymanke}/${IMAGE_NAME:-conduit}/frontend:${IMAGE_TAG:-latest}"
    ports:
      - "${FRONTEND_PORT:-8287}:80"
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge