services:
  backend:
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./backend:/usr/src/app/

  frontend:
    ports:
      - "4200:80"
    env_file:
      - .env.dev
    volumes:
      - ./frontend:/usr/share/nginx/html/
