services:
  backend:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
