services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - backend-data:/usr/src/app/
    restart: always
    healthcheck:
      test: ["CMD", "python3", "-c", "import sys, urllib.request; sys.exit(urllib.request.urlopen('http://localhost:8000/admin/login/').getcode() != 200)"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8282:80"
    restart: always
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend-data:
