name: Docker and Deploy

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io/henrymanke
  IMAGE_NAME: conduit
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.7.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image for frontend
        id: frontend-build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
      - name: Build and push Docker image for backend
        id: backend-build-and-push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker images for frontend
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.frontend-build-and-push.outputs.metadata.tags }}
          DIGEST: ${{ steps.frontend-build-and-push.outputs.digest }}
        run: |
          if [ -n "$DIGEST" ]; then
              echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
          else
              echo "Frontend image digest is empty. Skipping sign step for frontend."
          fi

      - name: Sign the published Docker images for backend
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.backend-build-and-push.outputs.metadata.tags }}
          DIGEST: ${{ steps.backend-build-and-push.outputs.digest }}
        run: |
          if [ -n "$DIGEST" ]; then
              echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
          else
              echo "Backend image digest is empty. Skipping sign step for backend."
          fi
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: SSH and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |

            # Install cosign if not present
            # if ! command -v cosign &> /dev/null; then
            #   echo "cosign not found, installing..."
            #   sudo wget https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -O /usr/local/bin/cosign
            #   sudo chmod +x /usr/local/bin/cosign
            # fi

            # Log into GitHub Container Registry
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin || exit 1

            # Extract the project name from the repository name
            PROJECT_NAME=$(basename "${{ github.repository }}")

            [ -z "${{ secrets.DEPLOY_PATH }}" ] && { echo "DEPLOY_PATH is not set"; exit 1; }
            
            # Navigate to the project directory on the server
            cd "${{ secrets.DEPLOY_PATH }}/${PROJECT_NAME}" || exit 1
            
            # Retry pulling frontend image
            n=0
            until [ $n -ge 3 ]; do
                docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest && break
                n=$((n+1))
                echo "Retry $n/3 for frontend image..."
                sleep 5
            done
            [ $n -eq 3 ] && { echo "Failed to pull frontend image after 3 attempts"; exit 1; }

            # Retry pulling backend image
            n=0
            until [ $n -ge 3 ]; do
                docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest && break
                n=$((n+1))
                echo "Retry $n/3 for backend image..."
                sleep 5
            done
            [ $n -eq 3 ] && { echo "Failed to pull backend image after 3 attempts"; exit 1; }

            # Clear and reinitialize TUF cache
            # rm -rf ~/.sigstore
            # n=0
            # until [ $n -ge 3 ]; do
            #     cosign initialize && break
            #     n=$((n+1))
            #     echo "Retrying TUF initialization... $n"
            #     sleep 5
            # done
            # [ $n -eq 3 ] && { echo "Failed to initialize TUF after 3 attempts"; exit 1; }

            # # Verify the frontend image
            # cosign verify \
            #   --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}@refs/heads/${{ github.ref_name }}" \
            #   --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            #   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest || { echo "Frontend image signature verification failed"; exit 1; }

            # # Verify the backend image
            # cosign verify \
            #   --certificate-identity "https://github.com/${{ github.repository }}/.github/workflows/${{ github.workflow }}@refs/heads/${{ github.ref_name }}" \
            #   --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
            #   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest || { echo "Backend image signature verification failed"; exit 1; }

            # Start services only if verification is successful
            docker compose up -d || { echo "Starting containers failed"; docker compose logs; exit 1; }